### PR TITLE
update jspm version.

### PR DESCRIPTION
**Pull request by subuta**
@ArtemGovorov I'm testing your repository with latest jspm(0.17)
and fixed incompatible settings with latest version.

plz merge this if you like it :)

BTW, In this setting i cannot get `source file coverage` working...
what do i need to chage?

### CODE REVIEW

**Comment by subuta** [comment]
I found when i set `format: 'amd'` in jspm.config.js and rewrite source/test module as a `amd` style.
`source file coverage` shows correctly. but What I want to do is source/test coverage with `format: esm` (ES6) syntax...

**Comment by ArtemGovorov** [comment]
@subuta Thanks, I have merged your PR and made another update (installed `jspm` as a local package, plus configured wallaby.js to use [Electron test runner](https://wallabyjs.com/docs/integration/electron.html)). It works for me as it, without changing the format to `amd` now. 

ws

Please try it to see if it works for you.

**Comment by subuta** [comment]
@ArtemGovorov thanks for merge and quick reply :).
Sorry the problem is `source files coverage`. I already found test file coverage is working well with 'Electron test runner' and 'phantomjs runner'

---

[Person.js]
image

[personSpec.js]
image

**Comment by ArtemGovorov** [comment]
Ah, got it. Wallaby.js doesn't treat `exports` themselves as coverable ranges, so there's no coverage displayed for the export. But if you add some branches or other executable statements, you'll see the coverage:
screen shot 2016-06-06 at 9 34 44 pm

**Comment by subuta** [comment]
@ArtemGovorov awesome! looks good and sorry for stupid question ;)

**Pull request merged**
